baseURL = "/"
languageCode = "en-us"
title = "Language Lessons Online with YOUR students and OUR teachers."
description = "Zamenhof.net is a White-label Online Language Tutoring Platform for Language Schools."
theme = "minimal-bootstrap-hugo-theme"

[permalinks]
  page = "/:filename/"

[params]

  includeBootstrapJs = true
  cookieConsent = true
  googleAnalytics = "UA-TODO-1"

[menu]

  [[menu.main]]
      identifier = "how-it-works"
      name = "How It Works"
      url = "/how-it-works/"
      weight = 1

  [[menu.main]]
      identifier = "about"
      name = "About"
      url = "/about/"
      weight = 2

  [[menu.main]]
      name = "Pricing"
      url = "/pricing/"
      weight = 3

  [[menu.main]]
      name = "Questions"
      url = "http://faq.zamenhof.net/"
      weight = 4

  [[menu.main]]
      identifier = "login"
      name = "Login"
      url = "https://admin.zamenhof.net/login"
      cssClass = "tets"
      weight = 5

  [[menu.main]]
      identifier = "request-access"
      name = "Request Access"
      url = "javascript:$('.request-modal-container').css('display','flex');"
      weight = 6


